### ISSUE TITLE
'transition'-ID has to be an integer

### ISSUE THREAD

**Issue by ZyanKLee** [lesstif/gitlab-jira-integration#6]
I get this error when trying to resolve an issue: 'transition'-ID has to be an integer
(It's roughly translated from german. The original error message was "'transition'-ID muss eine Ganzzahl sein", just in case this is relevant.)

``` php
[2015-07-24 06:32:29] lumen.DEBUG: hook received from   
[2015-07-24 06:32:29] lumen.INFO: eventType : Push Hook  
[2015-07-24 06:32:29] lumen.DEBUG: Commit : {
    "id": "3febf420655f69069b37c0683ecc62c6a800def5",
    "message": "fixes PRJ-235\n",
    "timestamp": "2015-07-24T08:32:24+02:00",
    "url": "https:\/\/gitlab.our.domain/group\/reponame\/commit\/3febf420655f69069b37c0683ecc62c6a800def5",
    "author": {
        "name": "My Name",
        "email": "my.email@our.domain"
    }
}  
[2015-07-24 06:32:29] lumen.ERROR: exception 'JiraRestApi\JIRAException' with message 'CURL HTTP Request Failed: Status Code : 400, URL:https://jira.our.domain/rest/api/2/issue/PRJ-235/transitions
Error Message : {"errorMessages":["'transition'-ID has to be an integer"],"errors":{}}' in /home/gji/gitlab-jira-integration/vendor/lesstif/php-jira-rest-client/src/JiraClient.php:176
Stack trace:
#0 /home/gji/gitlab-jira-integration/vendor/lesstif/php-jira-rest-client/src/Issue/IssueService.php(197): JiraRestApi\JiraClient->exec('/issue/PRJ-235/...', '{"transition":{...', 'POST')
#1 /home/gji/gitlab-jira-integration/app/Http/Controllers/GitlabController.php(93): JiraRestApi\Issue\IssueService->transition('PRJ-235', Object(JiraRestApi\Issue\Transition))
#2 /home/gji/gitlab-jira-integration/app/Http/Controllers/GitlabController.php(38): App\Http\Controllers\GitlabController->pushHook(Object(Illuminate\Http\Request))
#3 [internal function]: App\Http\Controllers\GitlabController->hookHandler(Object(Illuminate\Http\Request))
#4 /home/gji/gitlab-jira-integration/vendor/illuminate/container/Container.php(502): call_user_func_array(Array, Array)
#5 /home/gji/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1348): Illuminate\Container\Container->call(Array, Array)
#6 /home/gji/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1313): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#7 /home/gji/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1284): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\GitlabController), 'hookHandler', Array)
#8 /home/gji/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1252): Laravel\Lumen\Application->callControllerAction(Array)
#9 /home/gji/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1237): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#10 /home/gji/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1158): Laravel\Lumen\Application->handleFoundRoute(Array)
#11 /home/gji/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1390): Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#12 /home/gji/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1164): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#13 /home/gji/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1104): Laravel\Lumen\Application->dispatch(NULL)
#14 /home/gji/gitlab-jira-integration/public/index.php(28): Laravel\Lumen\Application->run()
#15 /home/gji/gitlab-jira-integration/server.php(12): require_once('/home/gji/gitlab-ji...')
#16 {main}  
```

in case it helps, there is the `storage/app/Push-Hook.json` at http://paste.ubuntu.com/11928864/

I tried both v0.6.2 and master@HEAD, but the error stays the same. Jira is at v6.3.15 and Gitlab at  v7.8.1. PHP 5.5.9-1ubuntu4.11 and composer 1.0-dev ran through your composer.json without errors.

**Comment by lesstif** [comment]
The "'transition'-ID has to be an integer" and HTTP 400 error  seems to be when you try to transition on already fixed or closed issue.

check PRJ-235 isssue's current status.

And open "http:///jira.our.domain/rest/api/2/issue/PRJ-235/transitions?expand=transitions.fields" in your browser for your jira website and issue number to find the available transition ID and name.

thanks.

**Comment by ZyanKLee** [comment]
PRJ-235's status is "new/not resolved". But I think I found the solution to my problem.
The example file has transition targets named "Resolved" and "Closed", but in our installation the transition targets are called "Resolve" and "Close". So changing the integration file to my values should fix the problems, doesn't it?

**Comment by lesstif** [comment]
Wow good to know, thanks!. My jira installation had transition targets are "Resolved" and "Closed".
So changing the config.integration.json 's "keywords":  field and try again and let me know the result.

``` json
"keywords": [
            [
                "Resolve",
                "[resolve|fix]"
            ],
            [
                "Close",
                "[close]"
            ]
        ]
```

![image](https://cloud.githubusercontent.com/assets/404534/8908180/7eea6c0e-34b5-11e5-8f68-5495bdbda8ef.png)

**Comment by ZyanKLee** [comment]
Hey. I got it working: just had to set the integration user to English
language. :-D
So everything is fine with the code, but this small fact could be added to
the docs.
